"""Wrap a generated grid JSON as a browser script: window.<NAME> = {...};

Usage:
    python wrap_asset.py country_grid.json COUNTRY_GRID ../../dashboard/assets/country_grid.js
"""
import sys

src, name, out = sys.argv[1:4]
with open(src, encoding="utf-8") as f:
    data = f.read().strip()
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write(f"// Generated by tools/dashboard_data — see tools/dashboard_data/README.md\n")
    f.write(f"window.{name} = {data};\n")
print(f"wrote {out}")
